dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    implementation('org.jetbrains.kotlin:kotlin-stdlib:2.3.0')
    implementation("org.jetbrains.kotlin:kotlin-reflect:2.3.0")

    jarJar(api("net.ptcrys:RegistryLib:${registry_lib_version}"))
    jarJar(api("com.lowdragmc.ldlib2:ldlib2-neoforge-26.1:${ldlib2_version}"))

    compileOnly("dev.vfyjxf:taffy:1.1.4")// Source: https://mvnrepository.com/artifact/dev.vfyjxf/taffy
    compileOnly("org.appliedenergistics:appliedenergistics2:${ae2_version}:api")
    compileOnly("top.theillusivec4.curios:curios-neoforge:${curios_version}+26.1.2:api")
    compileOnly("mezz.jei:jei-26.1.2-neoforge-api:${jei_version}")
    implementation("curse.maven:jade-324717:8326300")
    implementation("dev.toma.configuration:configuration-neoforge:${configuration_version}+26.1.2")

    runtimeOnly("org.appliedenergistics:guideme:${guideme_version}")
    runtimeOnly("org.appliedenergistics:appliedenergistics2:${ae2_version}")
    runtimeOnly("top.theillusivec4.curios:curios-neoforge:${curios_version}+26.1.2")
    runtimeOnly("mezz.jei:jei-26.1.2-neoforge:${jei_version}")

    testImplementation("org.junit.jupiter:junit-jupiter:6.0.1")
    testImplementation("com.google.guava:guava:33.5.0-jre")
    testImplementation("it.unimi.dsi:fastutil:8.5.18")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}
