# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
#org.gradle.jvmargs=
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

## Environment Properties
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
# The Minecraft version must agree with the Neo version to get a valid artifact
minecraft_version=26.1.2
# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraft_version_range=[26.1, 27)
# https://files.neoforged.neoforge.net/net/neoforged.neoforge/forge/
neo_version=26.1.2.54-beta
neo_version_range=[26.1.0.8-beta,)
loader_version_range=[4,)

## Mod Properties
mod_id=breacore
mod_name=BreakdownCore
mod_license=LGPLv3
mod_version=0.1.0
mod_group_id=net.phasetranscrystal
mod_authors=MonLandis, LeeQianXi, HehCrashes
mod_description=
mod_url=https://github.com/PhasetransCrystal/BreakdownCore

# Dependency Properties
guideme_version=26.1.12-beta
ae2_version=26.1.9-alpha
curios_version=15.0.0-beta.2
ldlib2_version=26.1.2.19
registry_lib_version=8.0.14
jei_version=29.6.2.31
modern_ui_version=3.13.0.4