modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory
license = "${mod_license}"

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforge.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL = "${mod_url}"
# A file name (in the root of the mod JAR) containing a logo for display
logoFile = "icon.png"
# A text field displayed in the mod UI
#credits="" #optional
# A text field displayed in the mod UI
authors = "${mod_authors}" #optional

# The description text for the mod (multi line!) (#mandatory)
description = '''${mod_description}'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
[[mixins]]
config = "${mod_id}.mixins.json"

# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

[[dependencies."${mod_id}"]]
# the modid of the dependency
modId = "neoforge" #mandatory
type = "required" #mandatory
versionRange = "${neo_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ae2"
type = "optional"
versionRange = "[${ae2_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "curios"
type = "optional"
versionRange = "[${curios_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "jei"
type = "optional"
versionRange = "[${jei_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "jade"
type = "optional"
versionRange = "[${jade_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "guideme"
type = "optional"
versionRange = "[${guideme_version},)"
ordering = "AFTER"
side = "BOTH"